# Question 2 Analysis-1
- Finding the bytes recieved by Hillary and Trump in Newspaper during US election phase: from 1 Aug 2016 till 7 Now 2016 i.e. before election day

In [7]:
import os
boston_api_key=os.getenv('BOSTON_API_KEY') #article_api_key=os.getenv('Article_Search_API')
boston_api_key

'f72x8VquhZjD3y1fCNIgxTJxy'

In [2]:
def download_file(url):
    local_filename = url.split('/')[-1]
    r = requests.get(url, stream=True)
    with open(local_filename, 'wb') as f:
        for chunk in r.iter_content(chunk_size=1024): 
            if chunk: # filter out keep-alive new chunks
                f.write(chunk)
    return local_filename

In [3]:
def convert(input):
    if isinstance(input, dict):
        return {convert(key): convert(value) for key, value in input.items()}
    elif isinstance(input, list):
        return [convert(element) for element in input]
    else:
        return input

In [4]:
import requests
import json
import datetime
import time
import sys
import urllib
import urllib.error
import logging
from urllib.error import HTTPError
def getArticles(query,date,api_key, json_file_path):
    # Take one page of NYTIMES for given date
    for page in range(1):
#       try:https://soda.demo.socrata.com/resource/earthquakes.json?$limit=5&$offset=5
#       url1 = "https://data.cityofboston.gov/resource/ufcx-3fdn.csv?$$app_token="+boston_api_key 
#        "https://data.cityofboston.gov/resource/ufcx-3fdn.csv?$limit=5"+ "&$offset="+5+ "&$$app_token="+ boston_api_key
#        requested_string = "https://data.cityofboston.gov/resource/ufcx-3fdn.json?q="+ query+ "&begin_date=" + date + "&end_date=" + date + "&page=" + str(page) + "&api-key=" + api_key
        requested_string = "https://data.cityofboston.gov/resource/ufcx-3fdn.csv?$limit=1000"+ "&$offset=" + str(page) + "&$$app_token=" + boston_api_key
        response = requests.get(requested_string) #urlopen(request_string)
        #print(type(response))
        #content = response.read().decode('utf-8')
        content = response.content.decode("utf-8")
        #print(content)
        if content:
            #print(content)
            #r = json.loads(content)
            #print(r)
            articles = convert(json.loads(content))
            # if there are articles here
            #r = content["response"]
            #print(r)
            if len(articles["response"]["docs"]) >= 1:
                #print("entering")
                json_file_name = getJsonFileName(query,date,page, json_file_path)
                json_file = open(json_file_name, 'w')
                json_file.write(content)
                json_file.close()
        time.sleep(3)
        continue

In [5]:
# helper function to iterate through dates
def daterange( start_date, end_date ):
    if start_date <= end_date:
        for n in range( ( end_date - start_date ).days + 1 ):
            yield start_date + datetime.timedelta( n )
    else:
        for n in range( ( start_date - end_date ).days + 1 ):
            yield start_date - datetime.timedelta( n )

In [6]:
fulldate=datetime.datetime.now()
def getJsonFileName(query,date, page, json_file_path):
    json_file_name = ".".join([query,date,str(page),'@',str(fulldate),'json'])
    json_file_name = "".join([json_file_path,'/',json_file_name])
    return json_file_name

In [7]:
def storeData():
    json_file_path = '/Users/rajusingh/midterm/Data/question2/HillaryTrump/'
    query =  'Hillary Clinton, Trump'
    #July 21 & July 28 â€” Trump & Clinton formally accepts the respec. nomination. Date taken from 1Aug till 7 Nov before elction
    
    api_key = article_api_key    
    start = datetime.date( year = 2016, month = 7, day = 1 )
    end = datetime.date( year = 2016, month = 11, day = 7 )
    log_file = "".join([json_file_path,'/',"getTimesArticles_testing.log"])
 
    logging.info("Getting started.") 
    for date in daterange( start, end ):
        date = date.strftime("%Y%m%d")
        logging.info("Working on %s." % date)
        getArticles(query,date,api_key,json_file_path)

In [ ]:
storeData()  #call the function

In [ ]:
import requests
import json
import datetime
import time
import sys
import urllib
import urllib.error
import logging
from urllib.error import HTTPError
def getArticles(query,date,api_key, json_file_path):
    # Take one page of NYTIMES for given date
    for page in range(1):
        requested_string = "https://data.cityofboston.gov/resource/ufcx-3fdn.csv?$limit=1000"+ "&$offset=" + str(page) + "&$$app_token=" + boston_api_key
        response = requests.get(requested_string) #urlopen(request_string)
        #print(type(response))
        #content = response.read().decode('utf-8')
        content = response.content.decode("utf-8")
        #print(content)
        if content:
            #print(content)
            #r = json.loads(content)
            #print(r)
            articles = convert(json.loads(content))
            # if there are articles here
            #r = content["response"]
            #print(r)
            if len(articles["response"]["docs"]) >= 1:
                #print("entering")
                json_file_name = getJsonFileName(query,date,page, json_file_path)
                json_file = open(json_file_name, 'w')
                json_file.write(content)
                json_file.close()
        time.sleep(3)
        continue

In [9]:
import requests

url = requested_string = "https://data.cityofboston.gov/resource/ufcx-3fdn.json?$limit=1000"+ "&$offset=" + str(5) + "&$$app_token=" + boston_api_key

response = requests.get(url)
if response.status_code == 200:
    data = response.json()

In [26]:
df=pd.DataFrame(data)
df

,compnos,day_week,domestic,fromdate,incident_type_description,location,main_crimecode,month,naturecode,reportingarea,reptdistrict,shift,shooting,streetname,ucrpart,weapontype,x,xstreetname,y,year
0,152033020,Thursday,No,2015-04-23T11:43:00.000,MedAssist,"{'coordinates': [0, 0], 'type': 'Point'}",MedAssist,4,EDP,0,C11,Day,No,ADAMS ST,Part three,Unarmed,NaN,NaN,NaN,2015
1,152015870,Thursday,No,2015-02-19T12:00:00.000,VAL,"{'coordinates': [0, 0], 'type': 'Point'}",VAL,2,MVA,0,C11,Day,No,WASHINGTON ST,Part Two,Unarmed,NaN,NaN,NaN,2015
2,152033134,Thursday,No,2015-04-23T17:50:00.000,MedAssist,"{'coordinates': [0, 0], 'type': 'Point'}",MedAssist,4,UNCONS,0,D4,First,No,HARRISON AV,Part three,Unarmed,NaN,NaN,NaN,2015
3,152033071,Thursday,No,2015-04-23T12:00:00.000,DRUG CHARGES,"{'coordinates': [0, 0], 'type': 'Point'}",18xx,4,IVPREM,0,C11,Day,No,GIBSON ST,Part Two,Other,NaN,NaN,NaN,2015
4,152033073,Thursday,No,2015-04-23T14:45:00.000,TOWED,"{'coordinates': [0, 0], 'type': 'Point'}",TOWED,4,IVMV,0,C6,Day,No,E 2ND ST,Part three,Unarmed,NaN,NaN,NaN,2015
5,152033070,Wednesday,No,2015-04-22T12:00:00.000,SexReg,"{'coordinates': [0, 0], 'type': 'Point'}",SexReg,4,IVPER,0,D4,Day,No,HARRISON AV,Part Two,Unarmed,NaN,NaN,NaN,2015
6,152033195,Thursday,No,2015-04-23T21:45:00.000,TRESPASS,"{'coordinates': [0, 0], 'type': 'Point'}",TRESPASS,4,ARREST,0,E13,First,No,CENTRE ST,Part Two,Unarmed,NaN,NaN,NaN,2015
7,152033109,Wednesday,No,2015-04-22T12:00:00.000,SexReg,"{'coordinates': [0, 0], 'type': 'Point'}",SexReg,4,IVPER,0,D4,Day,No,HARRISON AV,Part Two,Unarmed,NaN,NaN,NaN,2015
8,152033131,Friday,No,2015-04-10T20:15:00.000,VANDALISM,"{'coordinates': [0, 0], 'type': 'Point'}",14xx,4,VAND,0,C6,First,No,EIGHTH ST,Part Two,Unarmed,NaN,NaN,NaN,2015
9,152014306,Sunday,No,2015-02-22T13:00:00.000,PropDam,"{'coordinates': [0, 0], 'type': 'Point'}",PropDam,2,IVPREM,0,C11,Day,No,MOON ISLAND,Part three,Unarmed,NaN,NaN,NaN,2015
10,152032952,Thursday,No,2015-04-23T03:55:00.000,MedAssist,"{'coordinates': [0, 0], 'type': 'Point'}",MedAssist,4,IVPER,0,C11,Last,No,GIBSON ST,Part three,Unarmed,NaN,NaN,NaN,2015
11,152033026,Thursday,No,2015-04-23T11:00:00.000,InvPer,"{'coordinates': [0, 0], 'type': 'Point'}",InvPer,4,CD9,0,D4,Day,No,DARTMOUTH ST,Part three,Unarmed,NaN,NaN,NaN,2015
12,152033097,Monday,No,2015-03-23T15:00:00.000,AUTO THEFT,"{'coordinates': [0, 0], 'type': 'Point'}",07xx,3,LARCEN,0,E5,Day,No,CENTRE ST,Part One,Unarmed,NaN,NaN,NaN,2015
13,152033143,Thursday,No,2015-04-23T16:30:00.000,PropLost,"{'coordinates': [0, 0], 'type': 'Point'}",PropLost,4,PROP,0,C6,First,No,D ST,Part three,Unarmed,NaN,NaN,NaN,2015
14,152032971,Thursday,No,2015-04-23T08:40:00.000,TOWED,"{'coordinates': [0, 0], 'type': 'Point'}",TOWED,4,IVMV,0,B2,Day,No,DANUBE ST,Part three,Unarmed,NaN,NaN,NaN,2015
15,152033157,Thursday,No,2015-04-23T18:34:00.000,DRUG CHARGES,"{'coordinates': [0, 0], 'type': 'Point'}",18xx,4,ARREST,0,A1,First,No,ESSEX ST,Part Two,Unarmed,NaN,SURFACE RD,NaN,2015
16,152014731,Monday,No,2015-02-23T05:23:00.000,VAL,"{'coordinates': [0, 0], 'type': 'Point'}",VAL,2,MVA,0,C11,Last,No,RIVER ST,Part Two,Unarmed,NaN,WASHINGTON ST,NaN,2015
17,152033031,Thursday,No,2015-04-23T13:00:00.000,InvProp,"{'coordinates': [0, 0], 'type': 'Point'}",InvProp,4,HAZMAT,0,C6,Day,No,COURTHOUSE WY,Part three,Other,NaN,NaN,NaN,2015
18,152033111,Thursday,No,2015-04-23T17:00:00.000,MedAssist,"{'coordinates': [0, 0], 'type': 'Point'}",MedAssist,4,REQEP,0,C6,First,No,TERMINAL ST,Part three,Unarmed,NaN,NaN,NaN,2015
19,152033092,Thursday,No,2015-04-23T15:25:00.000,MVAcc,"{'coordinates': [0, 0], 'type': 'Point'}",MVAcc,4,MVA,0,E13,Day,No,SOUTH ST,Other,Unarmed,NaN,ST ROSE ST,NaN,2015
20,152032997,Thursday,No,2015-04-23T10:47:00.000,MVAcc,"{'coordinates': [0, 0], 'type': 'Point'}",MVAcc,4,MVA,0,D14,Day,No,CAMBRIDGE ST,Other,Other,NaN,N BEACON ST,NaN,2015
21,152033086,Wednesday,No,2014-11-12T15:30:00.000,OTHER LARCENY,"{'coordinates': [0, 0], 'type': 'Point'}",06xx,11,LARCEN,0,B2,Day,No,CENTRE ST,Part One,Unarmed,NaN,NaN,NaN,2014
22,152033190,Thursday,No,2015-04-23T20:10:00.000,CRIMES AGAINST CHILDREN,"{'coordinates': [0, 0], 'type': 'Point'}",20xx,4,IVPER,0,A7,First,No,SUMNER ST,Part Two,Unarmed,NaN,NaN,NaN,2015
23,152032976,Monday,No,2015-04-13T12:00:00.000,FRAUD,"{'coordinates': [0, 0], 'type': 'Point'}",11xx,4,IVPER,0,C6,Day,No,GAVIN WY,Part Two,Unarmed,NaN,NaN,NaN,2015
24,152033138,Thursday,No,2015-04-23T17:09:00.000,MedAssist,"{'coordinates': [0, 0], 'type': 'Point'}",MedAssist,4,REQP,0,C6,First,No,MASSACHUSETTS AV,Part three,Unarmed,NaN,NaN,NaN,2015
25,152033149,Thursday,No,2015-04-23T16:00:00.000,DRUG CHARGES,"{'coordinates': [0, 0], 'type': 'Point'}",18xx,4,IVPREM,0,C11,First,No,GIBSON ST,Part Two,Unarmed,NaN,NaN,NaN,2015
26,152033224,Thursday,No,2015-04-23T23:08:00.000,DRUG CHARGES,"{'coordinates': [0, 0], 'type': 'Point'}",18xx,4,ARREST,0,A1,First,No,EAST ST PL,Part Two,Other,NaN,NaN,NaN,2015
27,152032963,Thursday,No,2015-04-23T08:00:00.000,OTHER LARCENY,"{'coordinates': [0, 0], 'type': 'Point'}",06xx,4,LARCEN,0,C11,Day,No,WASHINGTON ST,Part One,Unarmed,NaN,NaN,NaN,2015
28,152033154,Thursday,No,2015-04-23T18:37:00.000,MedAssist,"{'coordinates': [0, 0], 'type': 'Point'}",MedAssist,4,ARREST,0,C6,First,No,ROSECLAIR ST,Part three,Unarmed,NaN,NaN,NaN,2015
29,152033018,Thursday,No,2015-04-23T12:25:00.000,OTHER LARCENY,"{'coordinates': [0, 0], 'type': 'Point'}",06xx,4,ARREST,0,D4,Day,No,HARRISON AV,Part One,Unarmed,NaN,NaN,NaN,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,130645272,Wednesday,No,2013-09-11T10:05:00.000,DRUG CHARGES,"{'coordinates': [-71.059735, 42.297541], 'type...",18xx,9,IVDRUG,355,C11,Day,No,GIBSON ST,Part Two,Unarmed,775275.7115,NaN,2933759.268,2013
971,130513636,Thursday,No,2013-08-15T18:00:00.000,OTHER LARCENY,"{'coordinates': [-71.063873, 42.325436], 'type...",06xx,8,IVPER,0,C6,First,No,ALLSTATE RD,Part One,Unarmed,774104.1328,4TH AV,2943918.604,2013
972,120637708,Tuesday,No,2012-10-09T10:10:00.000,SIMPLE ASSAULT,"{'coordinates': [-71.124361, 42.28369], 'type'...",08xx,10,ABRPT,561,E5,Day,No,CUMMINS HY,Part Two,Unarmed,757814.1441,NaN,2928627.903,2012
973,130555410,Monday,No,2013-09-02T09:02:00.000,MVAcc,"{'coordinates': [-71.012108, 42.393627], 'type...",MVAcc,9,MVANO,15,A7,Day,No,MCCLELLAN HY,Other,Unarmed,787960.0487,NaN,2968844.641,2013
974,142060805,Friday,No,2014-12-26T22:51:00.000,AGGRAVATED ASSAULT,"{'coordinates': [-71.086949, 42.341247], 'type...",04xx,12,ARREST,0,D4,First,No,HUNTINGTON AV,Part One,Other,767835.9698,NaN,2949649.585,2014
975,142050653,Thursday,No,2014-11-20T11:59:00.000,VAL,"{'coordinates': [-71.10278, 42.321941], 'type'...",VAL,11,IVMV,0,E13,Day,No,PRIESING ST,Part Two,Unarmed,763589.0394,ESTRELLA ST,2942593.855,2014
976,140016246,Thursday,No,2014-01-09T05:00:00.000,VANDALISM,"{'coordinates': [-71.07426, 42.313657], 'type'...",14xx,1,BEMVRT,327,B2,Last,No,WAYLAND ST,Part Two,Other,771316.8572,NaN,2939612.229,2014
977,140189555,Thursday,No,2014-03-27T22:00:00.000,PropLost,"{'coordinates': [-71.052242, 42.354304], 'type...",PropLost,3,LSTPRP,114,A1,First,No,ATLANTIC AV,Part three,Unarmed,777194.1083,NaN,2954455.002,2014
978,152038431,Sunday,No,2015-05-10T16:00:00.000,VAL,"{'coordinates': [0, 0], 'type': 'Point'}",VAL,5,VAND,0,D4,First,No,COLUMBUS AV,Part Two,Other,NaN,NaN,NaN,2015
979,152017702,Thursday,No,2015-03-05T07:00:00.000,InvProp,"{'coordinates': [0, 0], 'type': 'Point'}",InvProp,3,CD9,0,C6,Last,No,COURTHOUSE WY,Part three,Unarmed,NaN,NaN,NaN,2015
980,152024562,Sunday,No,2015-03-15T21:30:00.000,AGGRAVATED ASSAULT,"{'coordinates': [0, 0], 'type': 'Point'}",04xx,3,AB,0,A15,First,No,WALFORD WY,Part One,Firearm,NaN,NaN,NaN,2015
981,152038891,Tuesday,No,2015-05-12T14:53:00.000,VAL,"{'coordinates': [0, 0], 'type': 'Point'}",VAL,5,MVA,0,E18,Day,No,CUMMINS HY,Part Two,Unarmed,NaN,NaN,NaN,2015
982,152016810,Tuesday,No,2015-02-03T13:00:00.000,Service,"{'coordinates': [0, 0], 'type': 'Point'}",Service,2,CD4,0,D4,Day,No,HARVARD ST,Other,Unarmed,NaN,NaN,NaN,2015
983,152038574,Monday,No,2015-05-11T13:45:00.000,VAL,"{'coordinates': [0, 0], 'type': 'Point'}",VAL,5,MVA,0,C11,Day,No,GENEVA AV,Part Two,Other,NaN,NaN,NaN,2015
984,152038932,Tuesday,No,2015-05-12T17:46:00.000,SIMPLE ASSAULT,"{'coordinates': [0, 0], 'type': 'Point'}",08xx,5,CHDABU,0,C11,First,No,BOWDOIN ST,Part Two,Unarmed,NaN,HAMILTON ST,NaN,2015
985,152038120,Saturday,No,2015-05-09T23:34:00.000,AGGRAVATED ASSAULT,"{'coordinates': [0, 0], 'type': 'Point'}",04xx,5,AB,0,C6,First,No,EMERSON ST,Part One,Unarmed,NaN,K ST,NaN,2015
986,152038842,Tuesday,No,2015-05-12T13:48:00.000,FORGERY,"{'coordinates': [0, 0], 'type': 'Point'}",10xx,5,IVPER,0,C11,Day,No,DORCHESTER AV,Part Two,Unarmed,NaN,NaN,NaN,2015
987,152038396,Sunday,No,2015-05-10T23:58:00.000,OTHER LARCENY,"{'coordinates': [0, 0], 'type': 'Point'}",06xx,5,LARCEN,0,A7,Last,No,BENNINGTON ST,Part One,Unarmed,NaN,NaN,NaN,2015
988,152038724,Tuesday,No,2015-05-12T06:00:00.000,MedAssist,"{'coordinates': [0, 0], 'type': 'Point'}",MedAssist,5,EDP,0,C11,Last,No,WESTVILLE TR,Part three,Unarmed,NaN,NaN,NaN,2015
989,152038767,Friday,No,2015-05-08T20:15:00.000,AGGRAVATED ASSAULT,"{'coordinates': [0, 0], 'type': 'Point'}",04xx,5,IVPER,0,B2,First,No,ROXBURY ST,Part One,Knife,NaN,NaN,NaN,2015
990,152038812,Tuesday,No,2015-05-12T11:39:00.000,Argue,"{'coordinates': [0, 0], 'type': 'Point'}",Argue,5,IVPER,0,B2,Day,No,BLUE HILL AV,Part three,Unarmed,NaN,NaN,NaN,2015
991,152016854,Monday,No,2015-03-02T14:25:00.000,ROBBERY,"{'coordinates': [0, 0], 'type': 'Point'}",03xx,3,PERGUN,0,B2,Day,No,DUDLEY PL,Part One,Firearm,NaN,NaN,NaN,2015
992,152038651,Monday,No,2015-05-11T18:09:00.000,MedAssist,"{'coordinates': [0, 0], 'type': 'Point'}",MedAssist,5,EDP,0,E13,First,No,CENTRE ST,Part three,Unarmed,NaN,NaN,NaN,2015
993,152038976,Tuesday,No,2015-05-12T19:30:00.000,AUTO THEFT,"{'coordinates': [0, 0], 'type': 'Point'}",07xx,5,IVMV,0,E18,First,No,RIVER ST,Part One,Unarmed,NaN,BUSINESS ST,NaN,2015
994,152037325,Thursday,No,2015-05-07T12:17:00.000,BENoProp,"{'coordinates': [0, 0], 'type': 'Point'}",BENoProp,5,BE,0,B2,Day,No,CENTRE ST,Part One,Other,NaN,NaN,NaN,2015
995,152019754,Wednesday,No,2015-03-11T18:40:00.000,WEAPONS CHARGE,"{'coordinates': [0, 0], 'type': 'Point'}",15xx,3,ARREST,0,B2,First,No,HAROLD PARK,Part Two,Firearm,NaN,NaN,NaN,2015
996,152038632,Monday,No,2015-05-11T15:40:00.000,OTHER LARCENY,"{'coordinates': [0, 0], 'type': 'Point'}",06xx,5,LARCEN,0,D14,Day,No,WASHINGTON ST,Part One,Unarmed,NaN,NaN,NaN,2015
997,152038706,Tuesday,No,2015-05-12T00:45:00.000,ROBBERY,"{'coordinates': [0, 0], 'type': 'Point'}",03xx,5,AB,0,D4,Last,No,ALBANY ST,Part One,Other,NaN,NaN,NaN,2015
998,152020510,Saturday,No,2015-03-14T02:07:00.000,SIMPLE ASSAULT,"{'coordinates': [0, 0], 'type': 'Point'}",08xx,3,FIGHT,0,A1,Last,No,BOYLSTON PL,Part Two,Unarmed,NaN,NaN,NaN,2015
999,152038481,Sunday,No,2015-04-26T19:45:00.000,VANDALISM,"{'coordinates': [0, 0], 'type': 'Point'}",14xx,4,VAND,0,C6,First,No,ALLSTATE RD,Part Two,Unarmed,NaN,NaN,NaN,2015

In [23]:
a=url.split('/')
b=a[4].split('?')
file_name=b[0]

In [24]:
json_file = open('/Users/rajusingh/Final/data/file_name', 'w')
json_file.write(data)
json_file.close()

TypeError: write() argument must be str, not list

In [13]:
import pandas as pd
r=pd.read_json(data)
r
# data

TypeError: Expected String or Unicode